CREATE DATABASE IF NOT EXISTS `logistikdb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `logistikdb`;

CREATE USER 'logistikuser'@'localhost' IDENTIFIED BY '***';GRANT ALL PRIVILEGES ON *.* TO 'logistikuser'@'localhost' IDENTIFIED BY '***' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON *.* TO 'logistikuser'@'localhost' IDENTIFIED BY PASSWORD '*0DEDD82B7ACA947975ED7C5D30A7A0E94BDA7EE2' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `logistikdb`.* TO 'logistikuser'@'localhost';